language: c

os:
  - osx
  - linux
  
compiler:
  - gcc
  - clang

before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ]]; then 
  CC=gcc-4.9; 
  gcc-4.9 --version;
  fi'
  
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then 
  sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; 
  sudo apt-get update -qq;
  sudo apt-get install -y gcc-4.8;
  export CC="gcc-4.8"; 
  fi'

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script: make

after_script:
  - ./DS_Course_Notes
